---
name: Style

on:
    push:
        branches:
        -   master
    pull_request:
        branches:
        -   '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

    # Force to use color
env:
    FORCE_COLOR: true

jobs:
    style:
        name: Check style
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v3

        -   name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: '3.12'
                allow-prereleases: false

        -   name: Install dependencies
            run: python -m pip install pycodestyle "jsonschema>=2.6.0,<3.0.0"

        -   name: run jsonlint
            run: jsonlint -q boutiques/schema/descriptor.schema.json

        -   name: run pycodestyle
            run: pycodestyle --max-line-length=80 boutiques/*.py boutiques/tests/*.py
