---
    name: Style
    
    on:
        push:
            branches:
            -   master
        pull_request:
            branches:
            -   '*'
    
    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
    
    # Force to use color
    env:
        FORCE_COLOR: true

    jobs:
      python_style:
        name: Check for spelling errors
        runs-on: ubuntu-latest
    
        steps:
            -   name: Setup python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'
                    allow-prereleases: false

            -   name: Install dependencies
                run: python -m pip install pycodestyle

            -   name: run pycodestyle
                run: pycodestyle --max-line-length=80 boutiques/*.py boutiques/tests/*.py