---
name: test

on:
    push:
        branches:
        -   master
    pull_request:
        branches:
        -   '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

    # Force to use color
env:
    FORCE_COLOR: true

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v3

        -   uses: eWaterCycle/setup-apptainer@v2
            with:
                apptainer-version: 1.3.0

        -   name: Build docker image
            run: make docker_build

        -   name: Build apptainer def
            run: make docker2singularity
